version: '3.8'
services:
  db:
    image: postgres:13.4
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  forkpi:
    build:
      context: .
      dockerfile: ./forkpi/Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./forkpi/db.sqlite3:/opt/code/db.sqlite3
      - static_volume:/opt/code/static
      - shm:/dev/shm
    command: bash -c './scripts/run-gunicorn'
    restart: always
    depends_on:
      - db

  forkpi_proxy:
    build:
      context: .
      dockerfile: ./forkpi_proxy/Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./forkpi/db.sqlite3:/opt/code/db.sqlite3
    depends_on:
      - forkpi

  cron:
    build:
      context: .
      dockerfile: ./cron/Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./forkpi/db.sqlite3:/opt/code/db.sqlite3
    depends_on:
      - forkpi_proxy
    restart: always

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - forkpi
    volumes:
      - static_volume:/opt/code/static
      - shm:/dev/shm
    restart: always

volumes:
  static_volume:
  shm:
  pgdata:
