version: '3.8'
services:
  forkpi:
    build:
      context: .
      dockerfile: ./forkpi/Dockerfile
    env_file:
      - ./forkpi/.env
    ports:
      - 8000:8000
    container_name: forkpi
    volumes:
      - ./forkpi:/opt/code
    command: bash -c 'python manage.py runserver 0.0.0.0:8000'
