version: '3.8'
services:
  forkpi:
    build:
      context: .
      dockerfile: ./forkpi/Dockerfile
    env_file:
      - ./.env
    ports:
      - 8000:8000
    volumes:
      - ./forkpi/db.sqlite3:/opt/code/db.sqlite3
      - ./forkpi:/opt/code
    command: bash -c 'python manage.py runserver 0.0.0.0:8000'

  forkpi_proxy:
    build:
      context: .
      dockerfile: ./forkpi_proxy/Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./forkpi/db.sqlite3:/opt/code/db.sqlite3
      - ./forkpi_proxy:/opt/code
    depends_on:
      - forkpi

  cron:
    build:
      context: .
      dockerfile: ./cron/Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./forkpi/db.sqlite3:/opt/code/db.sqlite3
      - ./cron:/opt/cron
    depends_on:
      - forkpi_proxy

  db:
    image: postgres:13.4
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
